on: push
name: Build Latest
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Linux
      uses: ./.github/actions/build_linux
      env:
        RACK_SDK_VERSION: 2.0.3
    - name: Tag Head as Latest
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ./.github/actions/update_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REF: refs/heads/main
        TAG: latest
    - name: Upload Linux Release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ./.github/actions/update_asset
      env:
        ASSET_PATH: dist/vitamin-2.0.1-lin.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: latest
  buildWindows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build Windows
      uses: ./.github/actions/build_win
      env:
        RACK_SDK_VERSION: 2.0.3
    - name: Tag Head as Latest
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ./.github/actions/update_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REF: refs/heads/main
        TAG: latest
    - name: Upload Windows Release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ./.github/actions/update_asset
      env:
        ASSET_PATH: dist/vitamin-2.0.1-win.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: latest
# TODO: This doesn't work :(
#  buildOsx:
#    name: Build OSX
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@main
#    - name: Build OSX
#      uses: ./.github/actions/build_osx
#      env:
#        RACK_SDK_VERSION: 2.0.3
#    - name: Tag Head as Latest
#      uses: ./.github/actions/update_tag
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        REF: refs/heads/main
#        TAG: latest
#    - name: Upload OSX Release
#      uses: ./.github/actions/update_asset
#      env:
#        ASSET_PATH: dist/vitamin-2.0.1-osx.zip
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        RELEASE_TAG: latest
